export type RouteEntry = { route: string; file: string };

export const ROUTES: RouteEntry[] = [
  { route: "/", file: "index.html" },
  { route: "/2113555582/onlyfans", file: "2113555582/onlyfans.html" },
  { route: "/2113555582/onlyfans/likes", file: "2113555582/onlyfans/likes.html" },
  { route: "/2113587529/onlyfans", file: "2113587529/onlyfans.html" },
  { route: "/2113587529/onlyfans/likes", file: "2113587529/onlyfans/likes.html" },
  { route: "/2116129559/onlyfans", file: "2116129559/onlyfans.html" },
  { route: "/2116129559/onlyfans/likes", file: "2116129559/onlyfans/likes.html" },
  { route: "/2130573931/onlyfans", file: "2130573931/onlyfans.html" },
  { route: "/2130573931/onlyfans/likes", file: "2130573931/onlyfans/likes.html" },
  { route: "/2132768617/onlyfans", file: "2132768617/onlyfans.html" },
  { route: "/2132768617/onlyfans/likes", file: "2132768617/onlyfans/likes.html" },
  { route: "/2185296654/onlyfans", file: "2185296654/onlyfans.html" },
  { route: "/2185296654/onlyfans/likes", file: "2185296654/onlyfans/likes.html" },
  { route: "/abbyrao2_0", file: "abbyrao2_0.html" },
  { route: "/about", file: "about.html" },
  { route: "/acceptable-use-policy", file: "acceptable-use-policy.html" },
  { route: "/aiko_mitsuri", file: "aiko_mitsuri.html" },
  { route: "/antitraffickingstatement", file: "antitraffickingstatement.html" },
  { route: "/appeal", file: "appeal.html" },
  { route: "/billiondollarbabie", file: "billiondollarbabie.html" },
  { route: "/brand", file: "brand.html" },
  { route: "/caseboon", file: "caseboon.html" },
  { route: "/cdn-cgi/l/email-protection", file: "cdn-cgi/l/email-protection.html" },
  { route: "/celiiinexo", file: "celiiinexo.html" },
  { route: "/colympios", file: "colympios.html" },
  { route: "/contact", file: "contact.html" },
  { route: "/contract", file: "contract.html" },
  { route: "/cookies", file: "cookies.html" },
  { route: "/datingtash", file: "datingtash.html" },
  { route: "/dmca", file: "dmca.html" },
  { route: "/gentle_mikey", file: "gentle_mikey.html" },
  { route: "/help", file: "help.html" },
  { route: "/isla_moretti", file: "isla_moretti.html" },
  { route: "/lexiswilsontv", file: "lexiswilsontv.html" },
  { route: "/lifewithhails", file: "lifewithhails.html" },
  { route: "/lilyblairexo", file: "lilyblairexo.html" },
  { route: "/miudaisy", file: "miudaisy.html" },
  { route: "/my/banking", file: "my/banking/index.html" },
  { route: "/my/chats", file: "my/chats/index.html" },
  { route: "/my/collections", file: "my/collections.html" },
  { route: "/my/collections/user-lists/subscribers/active", file: "my/collections/user-lists/subscribers/active.html" },
  { route: "/my/collections/user-lists/subscriptions/active", file: "my/collections/user-lists/subscriptions/active.html" },
  { route: "/my/collections/user-lists/subscriptions/expired", file: "my/collections/user-lists/subscriptions/expired.html" },
  { route: "/my/notifications", file: "my/notifications.html" },
  { route: "/my/payments", file: "my/payments/index.html" },
  { route: "/my/payments/add_card", file: "my/payments/add_card.html" },
  { route: "/my/settings", file: "my/settings.html" },
  { route: "/my/settings/account", file: "my/settings/account.html" },
  { route: "/my/settings/notifications", file: "my/settings/notifications.html" },
  { route: "/my/tickets/create", file: "my/tickets/create.html" },
  { route: "/onlyfans", file: "onlyfans.html" },
  { route: "/platform-business-regulation-terms", file: "platform-business-regulation-terms.html" },
  { route: "/posts/create", file: "posts/create.html" },
  { route: "/privacy", file: "privacy.html" },
  { route: "/rebeccassecretxo", file: "rebeccassecretxo.html" },
  { route: "/referral-program-terms", file: "referral-program-terms.html" },
  { route: "/rynrynrynn", file: "rynrynrynn.html" },
  { route: "/sami_gonzalez", file: "sami_gonzalez.html" },
  { route: "/shelly_moss", file: "shelly_moss.html" },
  { route: "/sunneebuilds", file: "sunneebuilds.html" },
  { route: "/terms", file: "terms.html" },
  { route: "/transparency-center", file: "transparency-center.html" },
  { route: "/transparency-center/appeals", file: "transparency-center/appeals.html" },
  { route: "/transparency-center/complaints", file: "transparency-center/complaints.html" },
  { route: "/uk-vat-policy", file: "uk-vat-policy.html" },
  { route: "/usc2257", file: "usc2257.html" },
  { route: "/values", file: "values.html" },
  { route: "/yoursweetfox", file: "yoursweetfox.html" },
];

export const ROUTE_MAP: Record<string, string> = Object.fromEntries(
  ROUTES.map((entry) => [entry.route, entry.file])
);
